<a href="https://colab.research.google.com/github/ExcessGroups/Earthquake_EDA/blob/main/notebooks/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pwd

/content

In [ ]:
!ls

sample_data

In [ ]:
ls -l

total 4
drwxr-xr-x 1 root root 4096 Jun  4 13:32 sample_data/

In [ ]:
!ll

/bin/bash: line 1: ll: command not found

In [ ]:
!ll -ls

/bin/bash: line 1: ll: command not found

In [ ]:
!du -sh

55M	.

In [ ]:
!du -h

8.0K	./.config/configurations
88K	./.config/logs/2026.06.04
92K	./.config/logs
148K	./.config
55M	./sample_data
55M	.

In [ ]:
!mkdir Data_Analysis

In [ ]:
%cd Data_Analysis

/content/Data_Analysis

In [ ]:
!mkdir Data Notebooks Figures Scripts

In [3]:
import pandas as pd

earthquakes = {"magnitude": [3.2, 4.1, 2.8, 5.0, 3.7],
               "Depth": [12, 8, 20, 5, 15],
               "Station": ["AB01", "AB02", "AB01", "AB03", "AB02"],
               "Country": ["Nigeria", "Nigeria", "Cameroon", "Nigeria", "Ghana"]
}


df = pd.DataFrame(earthquakes)
df

   magnitude  Depth Station   Country
0        3.2     12    AB01   Nigeria
1        4.1      8    AB02   Nigeria
2        2.8     20    AB01  Cameroon
3        5.0      5    AB03   Nigeria
4        3.7     15    AB02     Ghana

In [ ]:
df.columns

Index(['magnitude', 'Depth', 'Station', 'Country'], dtype='object')

In [ ]:
df.shape

(5, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   magnitude  5 non-null      float64
 1   Depth      5 non-null      int64
 2   Station    5 non-null      object
 3   Country    5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.dtypes

magnitude    float64
Depth          int64
Station       object
Country       object
dtype: object

In [ ]:
df['magnitude']

0    3.2
1    4.1
2    2.8
3    5.0
4    3.7
Name: magnitude, dtype: float64

In [ ]:
df[['magnitude']]

   magnitude
0        3.2
1        4.1
2        2.8
3        5.0
4        3.7

In [ ]:
df.loc[0]

magnitude        3.2
Depth             12
Station         AB01
Country      Nigeria
Name: 0, dtype: object

In [ ]:
df.loc[:2]

   magnitude  Depth Station   Country
0        3.2     12    AB01   Nigeria
1        4.1      8    AB02   Nigeria
2        2.8     20    AB01  Cameroon

In [ ]:
df.loc[0:1, ['magnitude', 'Station']]

   magnitude Station
0        3.2    AB01
1        4.1    AB02

In [4]:
df[["magnitude", "Station"]]

   magnitude Station
0        3.2    AB01
1        4.1    AB02
2        2.8    AB01
3        5.0    AB03
4        3.7    AB02

In [6]:
df.loc[:3]

   magnitude  Depth Station   Country
0        3.2     12    AB01   Nigeria
1        4.1      8    AB02   Nigeria
2        2.8     20    AB01  Cameroon
3        5.0      5    AB03   Nigeria

In [10]:
df['Station'].dtype

dtype('O')

In [12]:
mask= df['magnitude'] > 4

In [13]:
df[mask]

   magnitude  Depth Station  Country
1        4.1      8    AB02  Nigeria
3        5.0      5    AB03  Nigeria

In [14]:
df[df['Country'] == 'Nigeria']

   magnitude  Depth Station  Country
0        3.2     12    AB01  Nigeria
1        4.1      8    AB02  Nigeria
3        5.0      5    AB03  Nigeria

In [15]:
df[df['Country'] != 'Nigeria']

   magnitude  Depth Station   Country
2        2.8     20    AB01  Cameroon
4        3.7     15    AB02     Ghana

In [16]:
df[df['Depth'] >= 15]

   magnitude  Depth Station   Country
2        2.8     20    AB01  Cameroon
4        3.7     15    AB02     Ghana

In [18]:
df[(df['Country'] =='Nigeria') & (df['magnitude'] > 4)]

   magnitude  Depth Station  Country
1        4.1      8    AB02  Nigeria
3        5.0      5    AB03  Nigeria

In [22]:
df[(df['Country'] == 'Nigeria') | (df['Country'] == 'Cameroon')]

   magnitude  Depth Station   Country
0        3.2     12    AB01   Nigeria
1        4.1      8    AB02   Nigeria
2        2.8     20    AB01  Cameroon
3        5.0      5    AB03   Nigeria

In [23]:
df[df['Station'] == 'AB01']

   magnitude  Depth Station   Country
0        3.2     12    AB01   Nigeria
2        2.8     20    AB01  Cameroon

In [24]:
df[(df['Country'] == 'Cameroon') | (df['Country'] == 'Ghana')]

   magnitude  Depth Station   Country
2        2.8     20    AB01  Cameroon
4        3.7     15    AB02     Ghana

In [25]:
df[(df['Country'] == 'Nigeria') & (df['Depth'] <= 10)]

   magnitude  Depth Station  Country
1        4.1      8    AB02  Nigeria
3        5.0      5    AB03  Nigeria

In [26]:
df.describe()

       magnitude     Depth
count   5.000000   5.00000
mean    3.760000  12.00000
std     0.850294   5.87367
min     2.800000   5.00000
25%     3.200000   8.00000
50%     3.700000  12.00000
75%     4.100000  15.00000
max     5.000000  20.00000

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   magnitude  5 non-null      float64
 1   Depth      5 non-null      int64
 2   Station    5 non-null      object
 3   Country    5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [28]:
df.columns

Index(['magnitude', 'Depth', 'Station', 'Country'], dtype='object')

In [30]:
df['Country'].unique()

array(['Nigeria', 'Cameroon', 'Ghana'], dtype=object)

In [31]:
df['Country'].value_counts()

Country
Nigeria     3
Cameroon    1
Ghana       1
Name: count, dtype: int64

In [32]:
df['Station'].value_counts()

Station
AB01    2
AB02    2
AB03    1
Name: count, dtype: int64

In [33]:
df.groupby('Country')['magnitude'].mean()

Country
Cameroon    2.8
Ghana       3.7
Nigeria     4.1
Name: magnitude, dtype: float64

In [34]:
df.groupby('Country').size()

Country
Cameroon    1
Ghana       1
Nigeria     3
dtype: int64

In [35]:
df.groupby('Country')['Depth'].max()

Country
Cameroon    20
Ghana       15
Nigeria     12
Name: Depth, dtype: int64

In [36]:
df.groupby('Country')['magnitude'].agg(['mean', 'max', 'min'])

          mean  max  min
Country
Cameroon   2.8  2.8  2.8
Ghana      3.7  3.7  3.7
Nigeria    4.1  5.0  3.2

In [37]:
df.groupby(['Country', 'Station']).size()

Country   Station
Cameroon  AB01       1
Ghana     AB02       1
Nigeria   AB01       1
          AB02       1
          AB03       1
dtype: int64

In [38]:
df.groupby('Country')['Depth'].mean()

Country
Cameroon    20.000000
Ghana       15.000000
Nigeria      8.333333
Name: Depth, dtype: float64

In [39]:
df.groupby('Country')['magnitude'].mean()

Country
Cameroon    2.8
Ghana       3.7
Nigeria     4.1
Name: magnitude, dtype: float64

In [40]:
df.groupby('Country')['magnitude'].agg(['mean','max','min', 'count'])

          mean  max  min  count
Country
Cameroon   2.8  2.8  2.8      1
Ghana      3.7  3.7  3.7      1
Nigeria    4.1  5.0  3.2      3

In [44]:
!mkdir -p 'data/raw'

In [45]:
!mkdir -p Earthquake_EDA/{data/raw,data/processed,notebooks,figures,outputs}

In [46]:
!find Earthquake_EDA

Earthquake_EDA
Earthquake_EDA/outputs
Earthquake_EDA/data
Earthquake_EDA/data/processed
Earthquake_EDA/data/raw
Earthquake_EDA/figures
Earthquake_EDA/notebooks

In [47]:
!tree

/bin/bash: line 1: tree: command not found

In [48]:
!apt-get install tree

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  tree
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 47.9 kB of archives.
After this operation, 116 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tree amd64 2.0.2-1 [47.9 kB]
Fetched 47.9 kB in 1s (48.7 kB/s)
Selecting previously unselected package tree.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../tree_2.0.2-1_amd64.deb ...
Unpacking tree (2.0.2-1) ...
Setting up tree (2.0.2-1) ...
Processing triggers for man-db (2.10.2-1) ...

In [49]:
!tree

.
├── data
│   ├── processed
│   └── raw
│       └── events.csv
├── Earthquake_EDA
│   ├── data
│   │   ├── processed
│   │   └── raw
│   ├── figures
│   ├── notebooks
│   └── outputs
└── sample_data
    ├── anscombe.json
    ├── california_housing_test.csv
    ├── california_housing_train.csv
    ├── mnist_test.csv
    ├── mnist_train_small.csv
    └── README.md

11 directories, 7 files

In [53]:
import os

os.listdir('./data/')

['processed', 'raw', '.ipynb_checkpoints']

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive